name: build

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                compiler: [gcc]
        env:
            CC: ${{ matrix.compiler }}
        steps:
            - uses: actions/checkout@v3
            - run: sudo apt-get update && sudo apt-get install -y gcc-multilib wget cpio qemu-system-x86 grub2 mtools xorriso libc6
            - run: make clean
            - run: make CC=gcc
            - run: nm -n kernel/kernel | awk 'NF==3'
            - run: make test CC=gcc
              timeout-minutes: 1
            - run: grub-file --is-x86-multiboot kernel/kernel
            - run: make cdrom.iso
